#!/usr/bin/env python3

import os
import sys

import xmltojson

def main():

    if not len(sys.argv) > 1:
        print('xml filename required...')
        sys.exit(1)

    xml_filename = sys.argv[1]

    option_version = ['v', '-v', '--v', 'version', '-version', '--version']
    option_file = ['f', '-f', '--f', 'file', '-file', '--file']

    if xmltojson._lists_share_element(sys.argv, option_version):
        xmltojson._usage()
        sys.exit()

    if not os.path.exists(xml_filename):
        print('File not found...')
        sys.exit(1)

    # Create filename for json output file
    json_filename = xmltojson._tr_xml_to_json_extension(xml_filename)

    # Grab xml from file
    xml_string = xmltojson._read_xml_file(xml_filename)

    # Translate xml to json from the string we got
    json_obj = xmltojson.parse(xml_string)

    # Create json output file
    if xmltojson._lists_share_element(sys.argv, option_file):
        xmltojson._write_output_file(json_filename, json_obj)
    else:
        print(json_obj)


if __name__ == "__main__":
    main()
